spring:
  datasource:
    # Use environment variables for production database config
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vadinvoicing}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

# JWT - must be set via environment variable
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in production

# H2 Console disabled in production
  h2:
    console:
      enabled: false

logging:
  level:
    eu.ageekatyourservice.vadinvoicing: INFO
    org.springframework.security: WARN

server:
  error:
    include-message: false
    include-stacktrace: never
